[package]
name = "binding-example"
version = "0.1.0"
authors = ["Joseph Henry <joseph.henry@zerotier.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#rustc-link-search = ["../../../lib/debug/macos-x86_64/"]

[dependencies]
