name: Code style compliance check
on: push

jobs:
  run:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Format code
        run: ./build.sh format-code

      - name: Commit changes
        uses: joseph-henry/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Code style fixes'
          add: '.'
